[package]
name = "stellar_vanity"
version = "0.1.0"
authors = ["rustee"]

[dependencies]
rand = "0.4"
sha2 = "0.7.0"
ed25519-dalek = "0.6.1"
base32 = "0.3.1"
crc16 = "0.3.4"
bytes = "0.4.6"
byteorder = "1.2.1"
